# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


# ===================================================================
# OPT-NC specific properties
# ===================================================================

opt:
    flux:
        config:
            jira:
                rootUrl: "https://kenichi.atlassian.net"
                login: "kenichibrun@hotmail.com"
                password: "simpleuser"
            otrs:
                rootUrl: "https://kenichi.atlassian.net"
                login: "kenichibrun@hotmail.com"
                password: "simpleuser"
        util:
            mySecret: ${random.value}
            myUuid: ${random.uuid}

